AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot application with SnapStart enabled

Globals:
  Function:
    Runtime: java21
    MemorySize: 2048
    Timeout: 30

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name for deployment
    
Resources:
  TodoListAppApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      TracingEnabled: true

  TodoListAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.serverless.proxy.spring.SpringDelegatingLambdaContainerHandler
      Role: !GetAtt TodoFunctionRole.Arn
      CodeUri: .
      Tracing: Active
      Environment:
        Variables:
          MAIN_CLASS: com.github.aws.tutorials.lambda.Application
          AWS_SERVERLESS_JAVA_CONTAINER_INIT_GRACE_TIME: 500
          DYNAMODB_TABLE: !Ref TodoTable
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions  
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY
            RestApiId: !Ref TodoListAppApi

  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${AWS::StackName}-todos-${Environment}
      PrimaryKey:
        Name: id
        Type: String

  TodoFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-todo-function-role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TodoFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt TodoTable.Arn

Outputs:
  TodoListEndpoint:
    Description: API Gateway Endpoint
    Value:
      Fn::Sub: https://${TodoListAppApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/